---
- name: linux_helper | Deploy profile configuration
  ansible.builtin.template:
    src: "profile.j2"
    dest: "/etc/profile.d/ansible.sh"
    owner: "root"
    group: "root"
    mode: "0644"
    force: "yes"
