---
- name: "linux_helper | Deploy modprobe.d conf files"
  ansible.builtin.template:
    src: "modprobe.j2"
    dest: "{{ '/etc/modprobe.d/' ~ vars['outer_item'] ~ '.conf' }}"
    group: "root"
    owner: "root"
    mode: "0644"
    force: "yes"
  loop: "{{ hostvars[inventory_hostname]['linux_helper'] |
    community.general.json_query(\"[].modprobe[].modprobes\" ~
    \"[?file_name=='\" ~ vars['outer_item'] ~ \"']\") | flatten(levels=1) }}"
  loop_control:
    loop_var: "linux_helper_modprobes"
    label: "{{ 'Deploy modprobe file: ' ~
      linux_helper_modprobes['file_name'] }}"
  notify:
    # https://access.redhat.com/discussions/1519283
    - "Run dracut"
