---

- name: "linux_helper | Include prereq tasks"
  ansible.builtin.import_tasks:
    file: "pre_requisite.yml"
- name: "linux_helper | Include deploy locale tasks"
  ansible.builtin.include_tasks:
    file: "deploy_locale.yml"
  when:
    - "vars['linux_helper_locale_settings']['locales'] is defined"
    - "vars['linux_helper_locale_settings']['locales'] != []"
- name: "linux_helper | Include deploy profile tasks"
  ansible.builtin.include_tasks:
    file: "deploy_profile.yml"
  when:
    - "vars['linux_helper_profile_settings'] is defined"
    - "vars['linux_helper_profile_settings'] != []"
- name: "linux_helper | Include deploy hostname tasks"
  ansible.builtin.include_tasks:
    file: "deploy_hostname.yml"
  when:
    - "vars['linux_helper_hostname_settings'] is defined"
    - "vars['linux_helper_hostname_settings'] != []"
    - "hostvars[inventory_hostname]['linux_helper'] |
       community.general.json_query(vars['linux_helper_set_hostname']) is
       defined"
    - "hostvars[inventory_hostname]['linux_helper'] |
       community.general.json_query(vars['linux_helper_set_hostname']) ==
       'true'"
  vars:
    linux_helper_set_hostname: "[].hostname[] |
      map(&set_hostname || 'false', @) | [0]"
- name: "linux_helper | Include deploy hosts tasks"
  ansible.builtin.include_tasks:
    file: "deploy_hosts.yml"
  when:
    - "vars['linux_helper_hosts_settings'] is defined"
    - "vars['linux_helper_hosts_settings'] != []"
    - "hostvars[inventory_hostname]['linux_helper'] |
       community.general.json_query(vars['linux_helper_set_hosts']) is
       defined"
    - "hostvars[inventory_hostname]['linux_helper'] |
       community.general.json_query(vars['linux_helper_set_hosts']) ==
       'true'"
  vars:
    linux_helper_set_hosts: "[].hosts[] | map(&set_hosts || 'false', @) | [0]"
- name: "linux_helper | Include modprobe executor"
  ansible.builtin.include_tasks:
    file: "modprobe_executor.yml"
  when:
    - "vars['linux_helper_modprobe_files'] is defined"
    - "vars['linux_helper_modprobe_files'] != []"
    - "hostvars[inventory_hostname]['linux_helper'] |
       community.general.json_query(vars['linux_helper_set_modprobe']) is
       defined"
    - "hostvars[inventory_hostname]['linux_helper'] |
       community.general.json_query(vars['linux_helper_set_modprobe']) ==
       'true'"
  vars:
    linux_helper_set_modprobe: "[].modprobe[] |
      map(&set_modprobe || 'false', @) | [0]"
- name: "linux_helper | Include deploy sudoers tasks"
  ansible.builtin.include_tasks:
    file: "deploy_sudoers.yml"
  when:
    - "vars['linux_helper_sudoers_settings'] is defined"
    - "vars['linux_helper_sudoers_settings'] != []"
- name: "linux_helper | Include deploy netconsole tasks"
  ansible.builtin.include_tasks:
    file: "deploy_netconsole.yml"
  when:
    - "vars['linux_helper_netconsole_settings'] is defined"
    - "vars['linux_helper_netconsole_settings'] != []"
    - "hostvars[inventory_hostname]['linux_helper'] |
       community.general.json_query(vars['linux_helper_set_netconsole']) is
       defined"
    - "hostvars[inventory_hostname]['linux_helper'] |
       community.general.json_query(vars['linux_helper_set_netconsole']) ==
       'true'"
  vars:
    linux_helper_set_netconsole:
      "[].netconsole[] | map(&set_netconsole || 'false', @) | [0]"
- name: "linux_helper | Include deploy krb5 tasks"
  ansible.builtin.include_tasks:
    file: "deploy_krb5.yml"
  when:
    - "vars['linux_helper_krb5_settings'] is defined"
    - "vars['linux_helper_krb5_settings'] != []"
