---
- include_tasks: pre_requisite.yml
- include_tasks: deploy_locale.yml
  when:
  - "hostvars[inventory_hostname]['linux_helper_locale'] is defined"
  - "hostvars[inventory_hostname]['linux_helper_locale'] != ''"
- include_tasks: deploy_hosts.yml
  when:
  - "hostvars[inventory_hostname]['linux_helper_hosts'] is defined"
  - "hostvars[inventory_hostname]['linux_helper_hosts'] != ''"
- include_tasks: modprobe_executor.yml
  when:
  - "vars['linux_helper_modprobes'] is defined"
  - "vars['linux_helper_modprobes'] != ''"
