---
- ansible.builtin.import_tasks:
    file: "pre_requisite.yml"
- ansible.builtin.include_tasks:
    file: "deploy_locale.yml"
  when:
    - "hostvars[inventory_hostname]['linux_helper_locale'] is defined"
    - "hostvars[inventory_hostname]['linux_helper_locale'] != ''"
- ansible.builtin.include_tasks:
    file: "deploy_profile.yml"
  when:
    - "hostvars[inventory_hostname]['linux_helper_profile'] is defined"
    - "hostvars[inventory_hostname]['linux_helper_profile'] != ''"
- ansible.builtin.include_tasks:
    file: "deploy_hostname.yml"
  when:
    - "vars['linux_helper_hostname'] is defined"
    - "vars['linux_helper_hostname'] != ''"
- ansible.builtin.include_tasks:
    file: "deploy_hosts.yml"
  when:
    - "hostvars[inventory_hostname]['linux_helper_hosts'] is defined"
    - "hostvars[inventory_hostname]['linux_helper_hosts'] != ''"
- ansible.builtin.include_tasks:
    file: "modprobe_executor.yml"
  when:
    - "vars['linux_helper_modprobes'] is defined"
    - "vars['linux_helper_modprobes'] != ''"
- ansible.builtin.include_tasks:
    file: "deploy_sudoers.yml"
  when:
    - "hostvars[inventory_hostname]['linux_helper_sudoers'] is defined"
    - "hostvars[inventory_hostname]['linux_helper_sudoers'] != ''"
- ansible.builtin.include_tasks:
    file: "deploy_krb5.yml"
  when:
    - "hostvars[inventory_hostname]['linux_helper_krb5'] is defined"
    - "hostvars[inventory_hostname]['linux_helper_krb5'] != ''"
