---
- name: "linux_helper | Include deploy modprobe tasks"
  ansible.builtin.include_tasks:
    file: "deploy_modprobe.yml"
  loop: "{{ lookup('ansible.builtin.vars', '_linux_helper_modprobe_files') |
    ansible.builtin.flatten(levels=1) }}"
  loop_control:
    loop_var: "outer_item"
