---
- name: "linux_helper | Assert that ansible facts gathered successfully"
  ansible.builtin.assert:
    that:
      - "hostvars[inventory_hostname]['ansible_facts']['os_family'] is defined"
    fail_msg: "'ansible_facts' not found. Please enable facts gathering"
    quiet: "true"
- name: "linux_helper | Add the OS specific varibles"
  ansible.builtin.include_vars:
    file: "{{ hostvars[inventory_hostname]['ansible_facts']['os_family'] +
      '.yml' }}"
- name: "linux_helper | Set linux_helper role facts"
  ansible.builtin.set_fact:
    _linux_helper_profile_settings: "{{ lookup('ansible.builtin.vars',
      'linux_helper') | community.general.json_query('[].profile | [0]') }}"
    _linux_helper_hostname_settings: "{{ lookup('ansible.builtin.vars',
      'linux_helper') | community.general.json_query('[].hostname[] | [0]') }}"
    _linux_helper_hosts_settings: "{{ lookup('ansible.builtin.vars',
      'linux_helper') | community.general.json_query('[].hosts[] | [0]') }}"
    _linux_helper_modprobe_files: "{{ (lookup('ansible.builtin.vars',
      'linux_helper') |
      community.general.json_query('[].modprobe[].modprobes[].file_name')) |
      ansible.builtin.unique() }}"
    _linux_helper_locale_settings: "{{ lookup('ansible.builtin.vars',
      'linux_helper') |
      community.general.json_query('[].locale[].locales[]') }}"
    _linux_helper_locale_langs: "{{ (lookup('ansible.builtin.vars',
      'linux_helper') |
      community.general.json_query('[].locale[].locales[].lang')) |
      ansible.builtin.unique() }}"
    _linux_helper_sudoers_settings: "{{ lookup('ansible.builtin.vars',
      'linux_helper') | community.general.json_query('[].sudoers[]') }}"
    _linux_helper_netconsole_settings: "{{ lookup('ansible.builtin.vars',
      'linux_helper') |
      community.general.json_query('[].netconsole[].netconsole[]') }}"
    _linux_helper_netconsole_systemd_dir:
      '/etc/systemd/system/netconsole.service.d'
    _linux_helper_krb5_settings: "{{ lookup('ansible.builtin.vars',
      'linux_helper') | community.general.json_query('[].krb5[]') }}"
  when:
    - "lookup('ansible.builtin.vars', 'linux_helper', default='')
      not in ['', [], '[]', None]"
- name: "linux_helper | Check visudo exists"
  ansible.builtin.stat:
    path: "/usr/sbin/visudo"
  register: "_linux_helper_visudo_result"
  failed_when: "_linux_helper_visudo_result['stat']['exists'] == False"
  when:
    - "lookup('ansible.builtin.vars', '_linux_helper_sudoers_settings',
      default='') not in ['', [], '[]', None]"
- name: "linux_helper | Create modprobe.d directory"
  ansible.builtin.file:
    path: "/etc/modprobe.d"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0755"
  when:
    - "lookup('ansible.builtin.vars', '_linux_helper_modprobe_files',
      default='') not in ['', [], '[]', None]"
- name: "linux_helper | Create profile.d directory"
  ansible.builtin.file:
    path: "/etc/profile.d"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0755"
  when:
    - "lookup('ansible.builtin.vars', '_linux_helper_profile_settings',
      default='') not in ['', [], '[]', None]"
- name: "linux_helper | Find exists tmpfiles configuration files"
  ansible.builtin.find:
    paths: "/etc/modprobe.d"
    recurse: "no"
    file_type: "file"
    patterns: "(.*).conf"
    excludes: "{{ _linux_helper_modprobe_exclude }}"
    use_regex: "true"
  register: "_linux_helper_modprobe_find_result"
  when:
    - "lookup('ansible.builtin.vars', '_linux_helper_modprobe_files',
      default='') not in ['', [], '[]', None]"
    - "lookup('ansible.builtin.vars', 'linux_helper', default='')
      not in ['', [], '[]', None]"
    - "lookup('ansible.builtin.vars', 'linux_helper') |
       community.general.json_query(lookup('ansible.builtin.vars',
       '_linux_helper_modprobe_drop_exists', default='')) == 'true'"
  vars:
    _linux_helper_modprobe_exclude: "{{ lookup('ansible.builtin.vars',
      '_linux_helper_modprobe_files', default=[]) |
      map('regex_replace', '^(.*)$', '\\1.conf') | list() }}"
    _linux_helper_modprobe_drop_exists: "[].modprobe[] |
      map(&drop_exists || 'false', @) | [0]"
- name: "linux_helper | Delete exists modprobe.d files"
  ansible.builtin.file:
    path: "{{ _linux_helper_modprobes_exist['path'] }}"
    state: "absent"
  loop: "{{ lookup('ansible.builtin.vars',
    '_linux_helper_modprobe_find_result')['files'] |
    ansible.builtin.flatten(levels=1) }}"
  loop_control:
    loop_var: "_linux_helper_modprobes_exist"
    label: "{{ 'Remove ' + _linux_helper_modprobes_exist['path'] }}"
  when:
    - "lookup('ansible.builtin.vars',
      '_linux_helper_modprobe_find_result')['files'] is defined"
