---
- name: "linux_helper | Install the netconsole packages for RedHat via dnf"
  ansible.builtin.dnf:
    name: "netconsole-service"
    state: "present"
    update_cache: "yes"
  when:
    - "hostvars[inventory_hostname]['ansible_os_family'] == 'RedHat'"
- name: "linux_helper | Install the netconsole packages in Debian derivatives"
  ansible.builtin.apt:
    name: "netconsole"
    state: "present"
    update_cache: "yes"
  when:
    - "hostvars[inventory_hostname]['ansible_os_family'] == 'Debian'"
