---
- name: "linux_helper | Install the required packages in Redhat derivatives"
  when:
    - "hostvars[inventory_hostname]['ansible_os_family'] == 'RedHat'"
  block:
    - name: "linux_helper | Update dnf cache"
      ansible.builtin.dnf:
        update_cache: "yes"
    - name: "linux_helper | Install package with dnf"
      ansible.builtin.dnf:
        name:
          "{{ hostvars[inventory_hostname]['linux_helper_netconsole_package'] }}"
        state: "present"
- name: "linux_helper | Install the required packages in Debian derivatives"
  when:
    - "hostvars[inventory_hostname]['ansible_os_family'] == 'Debian'"
  block:
    - name: "linux_helper | Update apt cache"
      ansible.builtin.apt:
        update_cache: "yes"
    - name: "linux_helper | Install package with apt"
      ansible.builtin.apt:
        name:
          "{{ hostvars[inventory_hostname]['linux_helper_netconsole_package'] }}"
        state: "present"
- name: "linux_helper | Install the required packages in ArchLinux
    derivatives"
  when:
    - "hostvars[inventory_hostname]['ansible_os_family'] == 'Archlinux'"
  block:
    - name: "linux_helper | Update pacman cache"
      community.general.pacman:
        update_cache: "yes"
    - name: "linux_helper | Install package with pacman"
      community.general.pacman:
        name:
          "{{ hostvars[inventory_hostname]['linux_helper_netconsole_package'] }}"
        state: "present"
