---
- name: "Daemon reload"
  ansible.builtin.systemd:
    daemon_reload: "yes"
- name: "Restart netconsole"
  ansible.builtin.systemd:
    name: "netconsole"
    state: "restarted"
  register: "linux_helper_netconsole_restart_result"
  ignore_errors: true
- name: "Run dracut"
  ansible.builtin.command:
    cmd: "dracut --regenerate-all --force"
  register: "dracut_regenerate_result"
  changed_when: "dracut_regenerate_result['rc'] == 0"
  failed_when: "dracut_regenerate_result['rc'] != 0"
  when:
    - "hostvars[inventory_hostname]['ansible_os_family'] == 'RedHat'"
